"use client";
import { useState } from "react";
import PetArt from "./PetArt";
import { PageTabs } from "./CompactPages";
import { LAUNCH_ART } from "@/lib/launchArt";
import { normalizeAppearance } from "@/lib/appearance";
import { DAILY_QUESTS, MAX_IGGIES } from "@/lib/gameData";
const PLACES=[['kennel','Willow Kennels','Visit your Iggies',LAUNCH_ART.kennel],['adopt','Adoption House','Meet a new friend',LAUNCH_ART.adoption],['closet','Velvet Ribbon','Open your wardrobe',LAUNCH_ART.wardrobe],['shop','Market Lane','Little treasures',LAUNCH_ART.market],['events','The Great Meadow','Choose a destination',LAUNCH_ART.meadow],['games','Arcade Lane','A little playtime',LAUNCH_ART.collection]];
export default function CompactHome({username,pets,news,questFor,onClaimQuest,onGo,promises,guided,guideStep,onGuide,onToggleGuide}){
 const [section,setSection]=useState('plaza');const featured=pets.find(p=>p.stage!=='egg')||pets[0];
 return <section className="compact-home"><PageTabs items={[['plaza','Meadow Plaza'],['board','Daily Board'],['news','Gazette'],['promise','Meadow Promise']]} active={section} onChange={setSection} label="Home pages"/>
 {section==='plaza'&&<div className="compact-plaza-grid"><aside className="compact-player-panel"><small>YOUR MEADOW COMPANION</small><div className="compact-player-art">{featured&&<PetArt speciesKey={featured.speciesKey} colorKey={featured.colorKey} stage={featured.stage} outfitKey={featured.outfitKey} appearance={normalizeAppearance(featured)} size={150}/>}</div><h3>{featured?.name||'Your first friend awaits'}</h3><p>{pets.length} / {MAX_IGGIES} Iggies at home</p><button className="btn btn-primary" onClick={()=>onGo('kennel')}>Visit my kennel</button></aside><div className="compact-plaza-main"><div className="compact-welcome-scene"><img src={LAUNCH_ART.meadow} alt="A flower-filled Iggy Meadow plaza" decoding="async" fetchPriority="high"/><div><small>WELCOME TO IGGY MEADOW</small><h1>Hello, {username}!</h1><p>Small paws. A world of stories.</p></div></div><div className="compact-destinations">{PLACES.map(([key,title,copy,art])=><button key={key} onClick={()=>onGo(key)}><img src={art} alt="" decoding="async"/><span><strong>{title}</strong><small>{copy}</small></span></button>)}</div></div><aside className="compact-today-panel"><h2>Today’s little joys</h2>{DAILY_QUESTS.map(q=>{const state=questFor(q.key);return <div className="compact-daily-row" key={q.key}><span><strong>{q.name}</strong><small>{state.claimed?'Tucked away ✓':`+${q.reward} seeds`}</small></span>{state.completed&&!state.claimed?<button className="btn btn-primary" onClick={()=>onClaimQuest(q.key)}>Claim</button>:<span className="compact-daily-state">{state.claimed?'✓':'❀'}</span>}</div>})}<div className="compact-bulletin"><small>THE MEADOW GAZETTE</small><h3>{news[0]?.title||'A gentle little world'}</h3><button className="btn btn-ghost" onClick={()=>setSection("news")}>Read the Gazette →</button></div></aside></div>}
 {section==='board'&&<div className="compact-noticeboard"><h2 className="section-title">Today’s Meadow Board</h2>{DAILY_QUESTS.map(q=>{const state=questFor(q.key);return <div className="quest-row" key={q.key}><div className="quest-copy"><strong>{q.name}</strong><small>{q.description}</small></div><span>+{q.reward} seeds</span>{state.completed&&!state.claimed?<button className="btn btn-primary" onClick={()=>onClaimQuest(q.key)}>Claim</button>:<span>{state.claimed?'Complete ✓':'Open'}</span>}</div>})}</div>}
 {section==='news'&&<div className="compact-noticeboard"><h2 className="section-title">The Meadow Gazette</h2>{news.map(n=><article className="compact-news" key={n.title}><h3>{n.title}</h3><p>{n.text}</p></article>)}</div>}
 {section==='promise'&&<div className="compact-noticeboard"><h2 className="section-title">The Meadow Promise</h2><label className="compact-guide-toggle"><input type="checkbox" checked={guided} onChange={e=>onToggleGuide(e.target.checked)}/> Gentle Guide</label>{guided&&<div className="compact-guide"><strong>{guideStep.title}</strong><span>{guideStep.text}</span><button className="btn btn-primary" onClick={onGuide}>{guideStep.label}</button></div>}<div className="compact-promise-grid">{promises.map(p=><article key={p.title}><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></div>}
 </section>;
}
